force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>This field that relates to the project object</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/To_do__c/To_do__c.object-meta.xml
<CustomObject>
    <label>To do</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To do</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/To_do__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>To do</relationshipLabel>
    <relationshipName>To_do</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectMilestoneController.cls
public with sharing class ProjectMilestoneController {
    
    @AuraEnabled
    public static Id createProjectWithMilestonesAndTasks(String valuesJson, string projectName, String ownerId) {        
        Map<String, Object> objMap = new Map<String, Object>(); 
        Map<String, Milestone__c> mapMilestonesById = new Map<String, Milestone__c>(); 
        Map<String, To_do__c> mapTodos = new Map<String, To_do__c>(); 
        
        Wrapper project = (Wrapper) JSON.deserialize(valuesJson, Wrapper.class);
        Project__c newProject = new Project__c(
            Name = projectName,
            OwnerId = ownerId
        );         
        insert newProject;
        
        for(Milestone milestone : project.listMilestones){
            Milestone__c newMilestone = new Milestone__c();
            newMilestone.name = milestone.name;
            newMilestone.Project__c = newProject.Id;
            mapMilestonesById.put( milestone.id, newMilestone);
        }
        
        insert mapMilestonesById.values();
        
        
        for(Todos todo : project.listToDos){
            To_do__c todoObj = new To_do__c();
            todoObj.name = todo.name;
            todoObj.Milestone__c = mapMilestonesById.get(todo.idMilestone).id;
            mapTodos.put(todo.id, todoObj);
        }
        
        insert mapTodos.values();

        return newProject.id;
    }
    
    public class Wrapper{
        @AuraEnabled public List<Milestone> listMilestones;
        @AuraEnabled public List<Todos> listToDos;
    }
    public class Milestone{
        @AuraEnabled public string id;
        @AuraEnabled public string name;        
    }
    public class Todos{
        @AuraEnabled public string id;
        @AuraEnabled public string name; 
        @AuraEnabled public string idMilestone;        
    }
        

}