force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>This field that relates to the project object</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/To_do__c/To_do__c.object-meta.xml
<CustomObject>
    <label>To do</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To do</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/To_do__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>To do</relationshipLabel>
    <relationshipName>To_do</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectMilestoneControllerTest.cls
@isTest
public with sharing class ProjectMilestoneControllerTest {


@IsTest
    public static void createProjectWithMilestonesAndTasksTest(){
        String json = '{"listMilestones": [{"id": "milestone1", "name": "name1"},'+
        '{"id": "milestone2", "name": "name2"},'+
        '{"id": "milestone3", "name": "name3"}],'+
        '"listToDos": [{"id": "todo1", "name": "todo1", "idMilestone": "milestone1"},'+
        '{"id": "todo2", "name": "todo2", "idMilestone": "milestone2"},'+
        '{"id": "todo3", "name": "todo3", "idMilestone": "milestone3"}]}';

        String projectName = 'Project1';
        String ownerId = UserInfo.getUserId();

        Test.startTest();
        ProjectMilestoneController.createProjectWithMilestonesAndTasks(json, projectName, ownerId);
        Test.stopTest();
        
        List<To_do__c> todos = [SELECT Id, Name, Milestone__c FROM To_do__c];
        List<Milestone__c> milestones = [SELECT Id, Name, Project__c FROM Milestone__c];
        Project__c project = [SELECT Id, Name, OwnerId FROM Project__c];

        System.assertEquals(3, todos.size());
        System.assertEquals(3, milestones.size());
        System.assertEquals(projectName, project.Name);
        System.assertEquals(ownerId, project.OwnerId);
    }
}