force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>This field that relates to the project object</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>A field to show the current status of the project.</description>
    <inlineHelpText>Not Started = 0%
In Progress &gt;= 1% and &lt;= 99%
Complete = 100%</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MilestonesTriggerHandler.cls
public with sharing class MilestonesTriggerHandler {
    public static void calculatePercentToMilestone(List<Milestone__c> listNewmilestones, Map<Id,Milestone__c> oldMap){
        Set<Id> setIdProjects = new Set<Id>();
        Set<Id> setIdsDisconsider = new Set<Id>();

        if(Trigger.isDelete){
            for(Milestone__c milestone : oldMap.values()){                
                setIdProjects.add(milestone.Project__c);
                setIdsDisconsider.add(milestone.id);
            }
        }else{
            for(Milestone__c milestone : listNewmilestones){
                if(Trigger.isUpdate){
                    if(milestone.status__c != oldMap.get(milestone.Id).status__c){ 
                        setIdProjects.add(milestone.Project__c);
                    }
                }
                else{
                    setIdProjects.add(milestone.Project__c);
                }
            }
        }

        if(setIdProjects.size() > 0){
            Map<Id,Project__c> mapProjectsUpp = new Map<Id,Project__c>();
            Project__c projectInstance;
            Boolean hasAnyCompleteItem,anyoneStarted,notInitiated;

            for(Project__c project : [SELECT Id, Status__c, (SELECT Id, Status__c FROM Milestones__r WHERE Id NOT IN :setIdsDisconsider) FROM Project__c WHERE Id IN :setIdProjects]){
                hasAnyCompleteItem = false;
                anyoneStarted = false;
                notInitiated = false;
                
                projectInstance = new Project__c();
                projectInstance.id = project.id;

                for(Milestone__c milestone : project.Milestones__r){
                    if(milestone.Status__c == 'Complete') hasAnyCompleteItem = true;
                    else if(milestone.Status__c == 'In Progress') anyoneStarted = true;
                    else notInitiated = true;
                }

                projectInstance.Status__c = hasAnyCompleteItem && !anyoneStarted && !notInitiated ? 'Complete' : (anyoneStarted || hasAnyCompleteItem) ? 'In Progress' : 'Not Started';
                
                if(project.Status__c != projectInstance.Status__c) mapProjectsUpp.put(projectInstance.id, projectInstance);
            }
            
            UPDATE  mapProjectsUpp.values();
        }
    }
}