force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>This field that relates to the project object</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>A field to show the current status of the project.</description>
    <inlineHelpText>Not Started = 0%
In Progress &gt;= 1% and &lt;= 99%
Complete = 100%</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/To_do__c/To_do__c.object-meta.xml
<CustomObject>
    <label>To do</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To do</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/To_do__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>To do</relationshipLabel>
    <relationshipName>To_do</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TodoTriggerHandlerTest.cls
@isTest
public with sharing class TodoTriggerHandlerTest {
    @isTest
    public static void TodoTriggerHandlerTest() {
        Project__c project = DataFactory.createProject();
        insert project;

        Milestone__c milestone = DataFactory.createMilestone('Test', project.Id);
        insert milestone;

        To_do__c todo = DataFactory.createTodo('Test', milestone.Id);
        insert todo;

        todo.Status__c = 'In Progress';
        UPDATE todo;

        Test.startTest();
        Milestone__c milestoneSearched = [SELECT Status__c FROM Milestone__c  WHERE Name = 'Test' LIMIT 1 ];

        System.Assert.areEqual('In Progress', milestoneSearched.Status__c);
        Test.stopTest();
    }

     @isTest
    public static void TodoTriggerHandlerTestDelete() {
        Project__c project = DataFactory.createProject();
        insert project;

        Milestone__c milestone = DataFactory.createMilestone('Test', project.Id);
        insert milestone;

        To_do__c todo = DataFactory.createTodo('Test', milestone.Id);
        insert todo;

        

        Test.startTest();
        todo.Status__c = 'Complete';
        UPDATE todo;

        Milestone__c milestoneSearched = [SELECT Status__c FROM Milestone__c  WHERE Name = 'Test' LIMIT 1 ];
        System.Assert.areEqual('Complete', milestoneSearched.Status__c);

        delete todo;
        milestoneSearched = [SELECT Status__c FROM Milestone__c  WHERE Name = 'Test' LIMIT 1 ];
        System.Assert.areEqual('Not Started', milestoneSearched.Status__c);

        Test.stopTest();
    }
}